#### general settings
name: T
use_tb_logger: false
model: srgan
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:  # the 1st test dataset
    name: DF2K
    mode: LQGT
    dataroot_GT: ../../dataset/DF2K/HR/train
    dataroot_LQ: ../../dataset/DF2K/4X/train
    dataroot_T_OOS_map: ../../dataset/DF2K/Local_LPIPS_min_dn
#    dataroot_T_OOS_map: ../../SROT/LPIPS-Map-Gen/T_OOS_Map/ESRGAN-SROT-M1234-v2-4x/Local_LPIPS_min_dn

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 4
    GT_size: 256
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DF2K_val_X4
    mode: LQGT
    dataroot_GT: ../../dataset/DF2K/HR/val
    dataroot_LQ: ../../dataset/DF2K/4X/val

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 4
  out_nc: 3
  nf: 64
  nb: 23
network_C:
  which_model_C: UNet
  in_nc: 1475
  out_nc: 1
  nf: 64
  nb: 16
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64


#### path
path:
  pretrain_model_G: ../pretrained/ESRGAN-SROT-M1234-v2-4x.pth
  pretrain_model_C: ~
#  resume_state: ../experiments/DFT/training_state/35000.state
#  resume_state_C: ../experiments/DFT/models/35000_C.pth
#  strict_load_C: true
#  resume_state_C: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99

  lr_C: !!float 1e-4
  weight_decay_C: 0
  beta1_C: 0.9
  beta2_C: 0.99

  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
